const ID_SEPARATOR = ":";

/**
 * Type alias for entity IDs used throughout the app.
 * At runtime these are strings in the format "prefix:uuid" (e.g. "drawing:550e8400-...").
 * Backwards compatible with IDs generated by the old Math.random()-based system.
 */
export type UUID = string;

type IdPrefix = "drawing" | "folder";

function generateUUID(): string {
  return crypto.randomUUID();
}

function createId(prefix: IdPrefix): UUID {
  return `${prefix}${ID_SEPARATOR}${generateUUID()}`;
}

export const IdUtils = {
  createDrawingId(): UUID {
    return createId("drawing");
  },

  createFolderId(): UUID {
    return createId("folder");
  },

};
